version: 2

sources:
    - name: landing
      description: This is a replica of the Postgres database used by our app
      database: edp_dev #raw
      schema: landing #jaffle_shop
      tables:
          - name: landing_jaffle_shop_customers
            description: One record per customer.
          - name: landing_jaffle_shop_orders
            description: One record per order. Includes cancelled and deleted orders.